In [1]:
import pandas as pd

In [14]:
df_customers = pd.read_excel("2_detail_table_customers.xls")
df_customers.head()
df_customers.shape
df_customers.columns

Index(['ROUTE_ID', 'CUSTOMER_NUMBER', 'CUSTOMER_CODE', 'CUSTOMER_LATITUDE',
       'CUSTOMER_LONGITUDE', 'CUSTOMER_TIME_WINDOW_FROM_MIN',
       'CUSTOMER_TIME_WINDOW_TO_MIN', 'NUMBER_OF_ARTICLES', 'TOTAL_WEIGHT_KG',
       'TOTAL_VOLUME_M3', 'CUSTOMER_DELIVERY_SERVICE_TIME_MIN', ' '],
      dtype='object')

In [17]:
df_vehicles = pd.read_excel("3_detail_table_vehicles.xls")
df_vehicles.shape
df_vehicles.head()

,ROUTE_ID,VEHICLE_NUMBER,VEHICLE_CODE,VEHICLE_TOTAL_WEIGHT_KG,VEHICLE_TOTAL_VOLUME_M3,VEHICLE_FIXED_COST_KM,VEHICLE_VARIABLE_COST_KM,VEHICLE_AVAILABLE_TIME_FROM_MIN,VEHICLE_AVAILABLE_TIME_TO_MIN,RESULT_VEHICLE_TOTAL_DRIVING_TIME_MIN,RESULT_VEHICLE_TOTAL_DELIVERY_TIME_MIN,RESULT_VEHICLE_TOTAL_ACTIVE_TIME_MIN,RESULT_VEHICLE_DRIVING_WEIGHT_KG,RESULT_VEHICLE_DRIVING_VOLUME_M3,RESULT_VEHICLE_FINAL_COST_KM,
0,2946091,1,J92-T-826,1058,3.15,0,0.20,420,1080,NaN,NaN,NaN,NaN,NaN,NaN,
1,2946091,2,A69-O-649,1216,4.00,0,0.19,420,1080,NaN,NaN,NaN,NaN,NaN,NaN,
2,2946091,3,875-M-523,12509,20.84,0,0.51,420,1080,NaN,NaN,NaN,NaN,NaN,NaN,
3,2946091,4,O76-T-703,7271,15.50,0,0.22,420,1080,131.395,265.46,396.855,2004.460943,15.066668,25.10244,
4,2946091,5,O76-T-702,7271,15.50,0,0.22,420,1080,150.502,384.02,534.522,2404.214244,14.781528,26.97926,

In [20]:
df_depots = pd.read_excel("4_detail_table_depots.xls")
df_depots.shape
df_depots.columns

Index(['ROUTE_ID', 'DEPOT_NUMBER', 'DEPOT_CODE', 'DEPOT_LATITUDE',
       'DEPOT_LONGITUDE', 'DEPOT_AVAILABLE_TIME_FROM_MIN',
       'DEPOT_AVAILABLE_TIME_TO_MIN', ' '],
      dtype='object')

In [24]:
df_constraints = pd.read_excel("5_detail_table_constraints_sdvrp.xls")
df_constraints.shape
df_constraints.head()

,ROUTE_ID,SDVRP_CONSTRAINT_NUMBER,SDVRP_CONSTRAINT_CUSTOMER_CODE,SDVRP_CONSTRAINT_VEHICLE_CODE,
0,2946091,1,921336,875-M-523,
1,2946091,2,131768,875-M-523,
2,2946091,3,15208,875-M-523,
3,2946091,4,132531,O76-T-703,
4,2946091,5,132531,875-M-523,

In [28]:
df_cust = pd.read_excel("6_detail_table_cust_depots_distances.xls")
df_cust.head()

,ROUTE_ID,CUSTOMER_NUMBER,DEPOT_CODE,CUSTOMER_CODE,DIRECTION,DISTANCE_KM,TIME_DISTANCE_MIN,
0,2946091,1,1000,138087,DEPOT->CUSTOMER,31.173,34.815,
1,2946091,1,1000,138087,CUSTOMER->DEPOT,31.159,34.782,
2,2946091,2,1000,138157,DEPOT->CUSTOMER,47.352,54.527,
3,2946091,2,1000,138157,CUSTOMER->DEPOT,47.850,54.791,
4,2946091,3,1000,26,DEPOT->CUSTOMER,29.805,31.416,